### ISSUE TITLE
Not sure how to use this

### ISSUE THREAD

**Issue by ribbiks** [hussein-aitlahcen/HyperLightDrifterExporter#1]
Greetings, I'm interested in the extracted HLD sprites you posted in a now-deleted reddit thread:

https://www.reddit.com/r/hyperlightdrifter/comments/s00oh7/compiled_sprites/

Would you be able to repost that somewhere? Alternately, is there any documentation on how to use the dll produced by the code int his repo in order to extract the sprites?

Thanks!

**Comment by hussein-aitlahcen** [comment]
Here you go https://mega.nz/file/F18GiBDY#7aGFLM8yH9weq8V5tcWf-6CJ1NdDAOpx2XQI6yItUa0

**Comment by hussein-aitlahcen** [comment]
The SFXs are available on a link below this video https://www.youtube.com/watch?v=NZ5uwNyeIVA

**Comment by ribbiks** [comment]
Much appreciated. Thanks!
